### ISSUE TITLE
Can't build windows/amd64 on OS X

### ISSUE THREAD

**Issue by mr4x** [go-gl/glfw#151]
I'm trying to build windows/amd64 on Mac, but it fails with:

```
GOOS=windows GOARCH=amd64 go build
main.go:4:2: no buildable Go source files in /Users/Mr4x/go/src/github.com/go-gl/glfw/v3.1/glfw
```

And with CGO:

```
CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build
# github.com/go-gl/glfw/v3.1/glfw
In file included from ../github.com/go-gl/glfw/v3.1/glfw/native_windows.go:6:
./glfw/include/GLFW/glfw3native.h:78:11: fatal error: 'windows.h' file not found
 #include <windows.h>
          ^
1 error generated.
```

**Comment by ghost** [comment]
cross compiling with CGO known to work very badly. I recommend you spin up a VM or otherwise compile natively on windows

**Comment by dmitshur** [comment]
Yeah, I don't think cross-compiling packages that use cgo is supported.

**Comment by mem** [comment]
It is supported.

You have to have a C cross compiler (and a C++ one if needed).

That compiler has to a) know how to build binaries for Windows without any additional help (e.g., you call x86_64-windows-gcc or some such, without any additional arguments); or b) have a sysroot that you can use (e.g. x86_64-windows-gcc --sysroot=/home/user/path/to/windows/sysroot). In either case you need to set CC to this compiler, and if you are in the second case, you need to pass these arguments to the compiler using CGO_CFLAGS.

And this is as far as I can help, because I don't use neither OSX nor Windows.

**Comment by tapir** [comment]
Even if cross compiling is supported (Which I've never tried so I have no idea) this looks like a Go issue not glfw. I'm closing this. Feel free to reopen if you have a reason to.
