### ISSUE TITLE
glfw.CreateCursor causes a panic

### ISSUE THREAD

**Issue by rbudzko** [go-gl/glfw#156]
Hi,

glfw.CreateCursor causes a panic, due to improvement introduced in (I believe) golang 1.6. We are encountering "Go pointer to Go pointer" passed to CGO stack. We are talking about img_c structure in input.go and more specifically img_c.pixels around line ~390.

Problem can be solved by for example improvement like this:

c_pix, destructor := gl.Strs(string([]byte(m.Pix)) + "\x00")
img_c.pixels =  (_C.uchar)(_c_pix)

I'm more then happy to prepare pull request, but first I'd like to confirm if importing gl to glfw is appropriate. Additionally, destructor can be called at the end of glfw.CreateCursor, because C.glfwCreateCursor seems to copy the buffer.

Robert Budźko

**Comment by dmitshur** [comment]
Hi @rbudzko,

Thanks for reporting the issue. Your diagnosis sounds spot on to me.

> I'm more then happy to prepare pull request, but first I'd like to confirm if importing gl to glfw is appropriate.

In this case, it makes the most sense to simply copy the relevant snippet of code rather than importing all of `gl` for it.

There are many `gl` libraries, and unless the user imports the exact same one, it'll end up pulling in a large dependency unnecessarily.

Instead, feel free to just copy the `Strs` code from `gl` here. It's analogous to how each `gl` version package has its own. You should make it unexported since it's not going to be a part of `glfw`'s API.

Thanks for making a PR for this, I'll be happy to review it (or anyone else)!

**Comment by tapir** [comment]
I recommend _util.go_ for that function and also could you make a PR for devel branch v3.2 as well please.

Thank you.

**Comment by rbudzko** [comment]
@tapir thanks for a guidance! Prepared PR.
