### ISSUE TITLE
glfw cgo directory not supported by godep vendoring

### ISSUE THREAD

**Issue by alivesay** [go-gl/glfw#166]
As discussed in tools/godep/issues/422, go-gl/glfw cannot be used with godep.

Other packages seem to be moving C sources into the main package directory as a result.  Would this work for go-gl/glfw, or should we push godep for a better solution?

**Comment by hydroflame** [comment]
This package was built before the vendoring became popular, we'd rather not break everybody's code to support one of the oh-so-many vendoring tools.

**Comment by dmitshur** [comment]
> Other packages seem to be moving C sources into the main package directory as a result. Would this work for go-gl/glfw, or should we push godep for a better solution?

First, it wouldn't be nice because the glfw Go package directory already contains many .go files. Adding even more .c files there would be quite unreadable. But I don't think this argument on its own is very strong.

A bigger problem I see is that the GLFW C source itself uses multiple different directories:

https://github.com/go-gl/glfw/tree/master/v3.1/glfw/glfw

So we wouldn't be able to place it all in the same directory, not without _changing_ the GLFW C source. I'd rather not be forced to modify GLFW C source just to make a vendoring tool work. I think the ball is in the `godep` court to resolve this.

Disclaimer: I may be biased because I don't use vendoring and I don't use `godep` myself. But I'm trying to be impartial here. Still, if there are other counter-arguments, I'm happy to discuss this.

**Comment by tapir** [comment]
Didn't read all the details but looks like something to be pushed on godep side. Feel free to reopen if you see it fit.
