### ISSUE TITLE
Expose Window.data as *C.GLFWwindow

### ISSUE THREAD

**Issue by xlab** [go-gl/glfw#172]
Hi, was going to use GLFW to init the window and then pass it to the next (GUI) layer that expects a window handle for the further operation.

``` go
type Window struct {
    data *C.GLFWwindow
    // other fields
}
```

It seems that there is currently no way to get this handle from the outside. That blocks me from using the package. :(

**Comment by dmitshur** [comment]
Have you seen [`glfw.Window.GetX11Window`](https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#Window.GetX11Window) and similar funcs?

There's a different one for each OS. See:
- https://github.com/go-gl/glfw/blob/master/v3.2/glfw/native_darwin.go
- https://github.com/go-gl/glfw/blob/master/v3.2/glfw/native_linbsd.go
- https://github.com/go-gl/glfw/blob/master/v3.2/glfw/native_windows.go

**Comment by xlab** [comment]
Thing is that I don't want to get `ret := uintptr(C.workaround_glfwGetCocoaWindow(w.data))` but the `w.data` itself, which is `*C.GLFWwindow`, not a platform-native window handle. I have a [GUI layer](https://github.com/golang-ui/nuklear) that wants `*C.GLFWwindow` :)

**Comment by emidoots** [comment]
I'd be fine with exposing a new method in `https://github.com/go-gl/glfw/blob/master/v3.2/glfw/native.go` like:

```
// GetGLFWWindow returns a *C.GLFWwindow (i.e. the GLFW window itself). This can be used for
// passing the GLFW window handle to external C libraries.
func (w *Window) GetGLFWWindow() uintptr {
    ... return w.data
}
```

Want to send a PR?

**Comment by xlab** [comment]
Cool, I'll propose tomorrow. One more question though, what's up with 'uintptr' instead of 'unsafe.Pointer'?

**Comment by dmitshur** [comment]
Does GLFW (the C library, /cc @elmindreda) have an equivalent to the proposed `GetGLFWWindow()`? If not, how does it get by without one?

I'd be a little wary of adding methods not present in the C library. At least, I'd like to really understand why we're doing that, before doing it.

Also, style-wise, it should be `GLFWWindow()`, not `GetGLFWWindow()`. See https://golang.org/doc/effective_go.html#Getters:

> but it's neither idiomatic nor necessary to put Get into the getter's name.

**Comment by emidoots** [comment]
> Does GLFW (the C library, /cc @elmindreda) have an equivalent to the proposed GetGLFWWindow()? > If not, how does it get by without one?
> 
> I'd be a little wary of adding methods not present in the C library. At least, I'd like to really understand why we're doing that before doing it.

@shurcooL GLFW doesn't need one because the `GLFWWindow` type in C is literally what @xlab needs. In our case, we wrap it in a struct like:

```
type GLFWWindow struct {
    data *C.GLFWWindow
}
```

So if you need to pass the GLFW window created by this package into a separate C library (like @xlab is trying to do) then you need access to the private `data` field. Another option would be making that field public instead of adding a getter.

> Also, style-wise, it should be GLFWWindow(), not GetGLFWWindow(). See https://golang.org/doc/effective_go.html#Getters.

@shurcooL I am well aware, but suggested the `Get` prefix because that's what we use in all three files you linked (`GetCocoaWindow`, `GetX11Window`, etc).

> Cool, I'll propose tomorrow. One more question though, what's up with 'uintptr' instead of 'unsafe.Pointer'?

@xlab Go packages should not expose `unsafe.Pointer` across package boundaries because it means that you can write unsafe code without importing `unsafe` which makes determining where unsafety occurs harder to spot. This is just an idiomatic Go thing, `uintptr` and `unsafe.Pointer` are effectively identical types. (see https://golang.org/pkg/unsafe/#Pointer)

**Comment by emidoots** [comment]
BTW I suggest a method and not exposing the `data` field because that would mean exposing a `C` type which isn't good.

**Comment by xlab** [comment]
>  I suggest a method and not exposing the data field because that would mean exposing a C type which isn't good.

Yep, I meant the exposure via method in the body of this issue.

> This is just an idiomatic Go thing, uintptr and unsafe.Pointer are effectively identical types.

Sorry, they are not. From https://golang.org/pkg/unsafe/#Pointer:

1)  > The usual use for such a uintptr is to print it.
2) > Conversion of a uintptr back to Pointer is not valid in general.
3) > A uintptr is an integer, not a reference. Converting a Pointer to a uintptr creates an integer value with no pointer semantics. Even if a uintptr holds the address of some object, the garbage collector will not update that uintptr's value if the object moves, nor will that uintptr keep the object from being reclaimed.

The latter one means that this reference goes off radar. That's why everyone is tossing around unsafe.Pointers (storing them into map, etc), not the uintptr.

Moreover, even within the single case where `uintptr` is useful — the pointer arithmetic — it's illegal to do conversions in different expressions. The unsafe.Pointer -> uitnptr -> arithmetic -> unsafe.Pointer must be in the same expression only.

I advise you rewriting everything to be `unsafe.Pointer`, it's a good thing that API won't broke after that.

**Comment by xlab** [comment]
@slimsag @shurcooL 
Hey, so what's next?

**Comment by dmitshur** [comment]
After seeing @slimsag comment, I understand why this is needed, why it's `go-gl/glfw`-specific, and why the unfortunate non-idiomatic Get prefix makes sense.

I don't have thoughts on the uintptr vs unsafe.Pointer.

I'm pretty busy the next couple of weeks, but I can try to review a PR. I think you should come to an agreement with @slimsag first.

**Comment by emidoots** [comment]
Sorry @xlab for the delay.

Respectfully, I disagree. Those 3 bullet points you quoted are not applicable to CGO code, because that is memory that the Go runtime did not allocate (as in this case). To offer a counterpoint, https://godoc.org/golang.org/x/sys/unix#Syscall and https://godoc.org/golang.org/x/sys/windows#GetProcAddress return a `uintptr` for the same reasons of not exposing `unsafe.Pointer` to its users.

Also see the notes for https://golang.org/pkg/reflect/#Value.Pointer

> It returns uintptr instead of unsafe.Pointer so that code using reflect cannot obtain unsafe.Pointers without importing the unsafe package explicitly.

Taking parameters of `unsafe.Pointer` (https://golang.org/pkg/reflect/#Value.SetPointer and https://golang.org/pkg/reflect/#NewAt) is okay, because those must be obtained from somewhere (i.e. the unsafe package).

> The latter one means that this reference goes off radar. That's why everyone is tossing around unsafe.Pointers (storing them into map, etc), not the uintptr.

This is only true for memory allocated by Go, i.e. memory that doesn't come from `C`.

**Comment by xlab** [comment]
@slimsag makes sense now! Thanks.
