### ISSUE TITLE
glfw 3.3 beta support

### ISSUE THREAD

**Issue by mattkanwisher** [go-gl/glfw#195]
I know there is not an official release but the master has a bunch of cocoa bugs that have been fixed in last 9 months. Would you be open to a PR that has a new folder that tracks master?

**Comment by mattkanwisher** [comment]
Also possible I could back port some of the fixes to 3.2

**Comment by dmitshur** [comment]
Sure, that'd be great. Feel free to make a PR that adds a `v3.3/glfw` package and uses latest `master` of GLFW (the C library).

If it looks good and is stable, we can consider annotating it as a work in progress pre-release and merging it earlier.

We'd have to do this when GLFW 3.3+ is released anyway, so this is taking an incremental step in that direction. Less work in the future.

Do you know if there are any API changes since 3.2.1?

**Comment by tapir** [comment]
created a branch. closing this one.
