### ISSUE TITLE
package dependencies must be installed by hand

### ISSUE THREAD

**Issue by ghost** [go-gl/glfw#206]
Whe I run go get github.com/faiface/pixel

I have to install all dependencies by hand:
Like 
go get -u github.com/go-gl/glfw/v3.2/glfw
go get github.com/go-gl/mathgl/mgl32
go get golang.org/x/image/colornames
and
go get github.com/faiface/glhf

Isn't there a way that the fist go get install all dependencies automatic?

**Comment by tapir** [comment]
That's not a glfw problem. You can open a bug in https://github.com/golang/go

**Comment by ghost** [comment]
Sorry my mistake.. wrong repo

**Comment by dmitshur** [comment]
@norbertfuhs, when you do `go get -u`, it installs the package you specified and all of its dependencies.

So you just need to reverse the order in which you run it. Use `go get` on the target package first, instead of fetching dependencies first.

For example, if you do `go get -u github.com/shurcooL/Hover`, it will download `github.com/go-gl/mathgl/mgl64`, `github.com/goxjs/gl`, `github.com/go-gl/gl/v2.1/gl`, `github.com/goxjs/glfw`, `github.com/go-gl/glfw/v3.2/glfw`, and [all other dependencies](https://godoc.org/github.com/shurcooL/Hover?import-graph&hide=2), recursively and automatically. You'll have the final `Hover` binary installed in your `$GOPATH/bin` directory so you can run it right away.

**Comment by ghost** [comment]
Thanks great!
