### ISSUE TITLE
Q: Is the image format for icons image.RGBA?

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#209]
https://github.com/go-gl/glfw/blob/master/v3.2/glfw/window.go#L345

Does all platforms support pre-multiplied alpha RGBA instead of non-pre-multiplied alpha RGBA (NRGBA)? I feel like NRGBA is correct but am not sure.

**Comment by dmitshur** [comment]
I suspect we should be supporting `NRGBA` as the primary format. Either instead, or in addition to `RGBA`. Needs investigation.

**Comment by dmitshur** [comment]
GLFW (C library) docs state this for both cursor and window icon images:

```
The image data is 32-bit, little-endian, non-premultiplied RGBA, i.e. eight bits
per channel.  The pixels are arranged canonically as sequential rows, starting
from the top-left corner.
```

It was specified in https://github.com/glfw/glfw/commit/85a01bfd9b59c762dfdbd064083fa7be55cd1c80 via https://github.com/glfw/glfw/issues/426, and https://github.com/glfw/glfw/commit/beaeb0d4af53b62a86c7880b7180597c7f164145 via https://github.com/glfw/glfw/issues/1027.

So yes, I believe our code predates that and should be updated to use `image.NRGBA` instead of `image.RGBA`.

**Comment by hajimehoshi** [comment]
Thank you for the quick fix!
