### ISSUE TITLE
Expose glfwGetProcAddress in Context

### ISSUE THREAD

**Issue by kivutar** [go-gl/glfw#234]
See https://www.glfw.org/docs/latest/group__context.html#ga35f1837e6f666781842483937612f163

**Comment by tapir** [comment]
function pointers and cgo are very messy to implement. what use case do you have for it?
is go-gl/gl missing something?

**Comment by tapir** [comment]
you can't call the function that you get the adress for though. you need an
intermediary C function where you call it thus it makes more sense to have
specific C functions for the job and wrap them instead of getProcAddress.

**Comment by GeertJohan** [comment]
I believe the Drakirus/go-flutter-desktop-embedder project would benefit from a properly exported `glfwGetProcAddress`. Please see https://github.com/Drakirus/go-flutter-desktop-embedder/issues/68 for more details.

The go code over there doesn't need to call the functions that are returned by `glfwGetProcAddress`, but it does need to provide a callback wrapper around `glfwGetProcAddress` so that the third party library (Flutter) may properly resolve GL functions via glfw.

**Comment by GeertJohan** [comment]
Thanks @tapir
