### ISSUE TITLE
v3.2/glfw: MouseButtonCallback parameter mod should be renamed to mods

### ISSUE THREAD

**Issue by dmitshur** [go-gl/glfw#245]
This is a very minor issue. Filing so I don't forget.

https://godoc.org/github.com/go-gl/glfw/v3.2/glfw#MouseButtonCallback

The parameter `mod` should be `mods`, for consistency with other callbacks and the upstream GLFW (the C library) API.

**Comment by tapir** [comment]
Good catch. If I recall correctly there should be more things like this because in the very beginning I didn't care much about parameter names.

Also it would be nice if at some point we could switch to named return values when there is multiple things to return, just for better self documentation. In most of the cases it could save you a round-trip to the documentation page.
