### ISSUE TITLE
v3.3/glfw: 'Carbon/Carbon.h' file not found

### ISSUE THREAD

**Issue by weberc2-tempus** [go-gl/glfw#304]
When I try to install this on MacOS (10.15.3; go version `go1.15 darwin/amd64`), I get the following error:

```
$ go get -u github.com/go-gl/glfw/v3.3/glfw
go: github.com/go-gl/glfw/v3.3/glfw upgrade => v0.0.0-20201108214237-06ea97f0c265
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20201108214237-06ea97f0c265
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20201108214237-06ea97f0c265/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:184:
./glfw/src/cocoa_platform.h:30:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

I already have the `xcode-select` command line tools installed.

**Comment by dmitshur** [comment]
What happens if you try building the following C program:

```
$ cd $(mktemp -d)
$ cat <<EOF > main.c
#include <stdio.h>
#include <Carbon/Carbon.h>

int main() {
	printf("Hello Carbon.\n");
	return 0;
}
EOF
$ clang main.c
$ echo $?
```

**Comment by hedonghong** [comment]
> What happens if you try building the following C program:
> 
> ```
> $ cd $(mktemp -d)
> $ cat <<EOF > main.c
> #include <stdio.h>
> #include <Carbon/Carbon.h>
> 
> int main() {
> 	printf("Hello Carbon.\n");
> 	return 0;
> }
> EOF
> $ clang main.c
> $ echo $?
> ```

My computer had the same question.

I build the C program is:

main.c:2:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
main.c:2:10: note: did not find header 'Carbon.h' in framework 'Carbon' (loaded
      from '/System/Library/Frameworks')
1 error generated.
sky.he@bawangbieji tmp.LVJqel9h % echo $?
1
sky.he@bawangbieji tmp.LVJqel9h % 

My computer is macos catalina 10.15.1

**Comment by runeimp** [comment]
The Carbon API was removed from macOS in Catalina. Cocoa is what is left as well as CoreGraphics, etc.

**Comment by dmitshur** [comment]
That's odd. The aforementioned program builds successfully (and prints "Hello Carbon." if executed) for me both on:

-	macOS Monterey (12.0.1), M1 CPU
-	macOS Big Sur (11.6.1), Intel CPU

I expect that Carbon is deprecated, but is it really removed? Are there sources for that?

In any case, this seems like an issue for the GLFW C library tracker, since that is where the import of `<Carbon/Carbon.h>` comes from.

**Comment by runeimp** [comment]
@dmitshur From what I understand it's possible to add the Carbon framework to Xcode still (to support old project updates?) but it's not included by default anymore. Hm, I recently did a "Scorched Earth" fresh install of Big Sur recently and using find I see that the Carbon framework is included with both Apple Command Line Tools and Xcode. New policy? I haven't noticed Carbon in either for quite some time. Maybe I just missed it.

In any case Catalina is 64-bit only so maybe the discussion I saw about dropping Carbon support was simply that 32-bit Carbon apps won't run on Catalina. Not that the framework was removed from the Apple development tools. 🤷‍♂️

**Comment by dmitshur** [comment]
@runeimp Thanks for context. It the header was indeed removed in some versions of Xcode and then brought back, that could explain how some people (and not everyone) ran into this.

I'll close this since there's nothing to do in this Go wrapper for GLFW at this time, but if the issue returns, I encourage confirming that it also happens with the [C GLFW library](https://github.com/glfw/glfw), and if so, reporting it in [its issue tracker](https://github.com/glfw/glfw/issues).
