### ISSUE TITLE
Can we apply the gamepad issue fix before 3.3.5 is released?

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/glfw#324]
Now GLFW 3.3 has an issue that specific gamepads crashes the app immediately, and this will be fixed in 3.3.5 (https://github.com/glfw/glfw/issues/1763). This is a pretty serious problem in my library that uses GLFW (e.g. https://github.com/hajimehoshi/ebiten/issues/1229). As we're not sure when 3.3.5 is released, would it be possible to apply the patch before 3.3.5 is released?

CC @dmitshur

**Comment by dmitshur** [comment]
Given it is a serious issue, I think "backporting" the GLFW (C library) fix for it in go-glfw would be reasonable to do. It looks like a small patch that just removes those lines that send `GLFW_INVALID_VALUE`.

In this particular case, we can also consider applying a temporary workaround on the side of go-glfw. That is, to modify `glfw.Init` to accept `GLFW_INVALID_VALUE` as well until GLFW 3.3.5 is released and go-glfw updates to using it. Perhaps that's easier, since we'd only need to change Go code.

We should keep issue #292 open until this is fully resolved and workarounds are removed.

**Comment by hajimehoshi** [comment]
Thanks.

Now `invalidValue` is an error that should not be handled in go-gl/glfw. Can we change this to be handleable?

EDIT: NVM, `acceptError` can take `invalidError`.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/1229#issuecomment-880030199

It looks like we also need to fix `PollEvents`.

I've already reported this issue at the original GLFW issue (https://github.com/glfw/glfw/issues/1763#issuecomment-880036517)
