### ISSUE TITLE
Can we use precompiled binaries for cross compiling

### ISSUE THREAD

**Issue by hismailbulut** [go-gl/glfw#330]
If not, what is the way of cross compile to windows, linux and mac from windows or linux

**Comment by Jacalz** [comment]
This might not be the prefect answer to the question, but I think you might be able to use https://github.com/fyne-io/fyne-cross given that we are using `glfw` for Fyne as well. It makes things more or less as easy as they can possibly be because cross compiling C-code is, let's face it, far from ideal.

**Comment by hismailbulut** [comment]
Thanks for answering, I actually solved my issue with using github actions but this fyne seems promising. I will give it a try. Thank you much.

**Comment by Jacalz** [comment]
If this has been solved, should it perhaps be closed then?
